version: '3'
services:

  tag-watcher-svc:
    build:
      context: .
      args:
        # Choosing to hardcode the version for now since versioning doesn't give me any benefits right now
        # Could of ignored versioning all together, but now at least we have the option to deal with it later
        JAR_FILE: "target/tag-watcher-svc-0.0.1-SNAPSHOT.jar"

  envoy-front-proxy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    expose:
      - "80"
      - "8001"
    ports:
      - "80:8000"
      - "8001:8001"

#  envoy-tag-watcher-svc:
#    build:
#      context: .
#      dockerfile: Dockerfile-tagwatchersvcenvoy
#    volumes:
#      - ./tag-watcher-svc.yaml:/etc/tag-watcher-svc.yaml

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 9411:9411
      - 8081:16686

  statsd_exporter:
    image: prom/statsd-exporter:latest
    ports:
      - "9125:9125"
      - "9102:9102"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus.yaml"


networks:
  envoymesh: {}
