version: '3'
services:
  tag-watcher-svc:
    build:
      context: .
      args:
        # Choosing to hardcode the version for now since versioning doesn't give me any benefits right now
        # Could of ignored versioning all together, but now at least we have the option to deal with it later
        JAR_FILE: "target/tag-watcher-svc-0.0.1-SNAPSHOT.jar"
    ports:
      - "8080:8080"